import:
	eos.moe.dragoncore.api.KeyPressEvent

on KeyPressEvent:
#	broadcast "%event.isCancelled()%|%event.getKey()%|%event.getKeys()%"

command /resetHealth <boolean>:
	trigger:
		set health of command sender to 1
		set level of command sender to 0
		if arg-1 is true:
			set yml value "stats.healthTier" from file "plugins/PlayerData/%name of command sender%.yml" to 5
			set yml value "stats.manaTier" from file "plugins/PlayerData/%name of command sender%.yml" to 1
			kick command sender
command /getTestItem:
	trigger:
		command sender is op
		set {_sender} to command sender
		give 5 diamond named "附魔星鱼" to {_sender}
		give 4 diamond named "魔力星" to {_sender}
		give a diamond named "彗星碎片" to {_sender}
		give a diamond named "飘渺之核" to {_sender}
		give a diamond named "幻影之心" to {_sender}
		
		give 15 emerald named "生命水晶" to {_sender}
		give 20 emerald named "生命果" to {_sender}
		give a emerald named "血橙" to {_sender}
		give a emerald named "奇迹之果" to {_sender}
		give a emerald named "旧神浆果" to {_sender}
		give a emerald named "龙果" to {_sender}
command /HP:
	trigger:
		set {_ht} to yml value "stats.healthTier" from file "plugins/PlayerData/%name of command sender%.yml"
		set {_mt} to yml value "stats.manaTier" from file "plugins/PlayerData/%name of command sender%.yml"
		broadcast "%health of command sender%/%max health of command sender%|%{_ht}%"
		broadcast "%level of command sender%/%(metadata ""attrMap"" of command sender).get(""maxMana"")%|%{_mt}%"