VersionLiteLoader:False
VersionForge:14.23.5.2859
Info:正式版 1.12.2, Forge 14.23.5.2859
VersionVanilla:12.0.2
VersionOriginalMain:12
VersionApiCode:14232859
VersionVanillaName:1.12.2
ReleaseTime:2017-09-18 04:39
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
VersionArgumentIndieV2:False
VersionOriginalSub:2
VersionOriginal:1.12.2
VersionArgumentIndie:0
State:6
